### ISSUE TITLE
color-convert dependency issue

### ISSUE THREAD

**Issue by procopenco** [chartjs/chartjs-color#3]
When I run karma-typescript  unit tests, I get an issue related to color-convert dependency.
Please, update color-convert dependency from 0.5.3 to latest version.
Thank you.

**Comment by Qix-** [comment]
What is the issue, specifically?

**Comment by phryniszak** [comment]
it is buggy,

function rgb2hwb(rgb) {
  var r = rgb[0],
      g = rgb[1],
      b = rgb[2],
      h = rgb2hsl(rgb)[0],
      w = 1/255 * Math.min(r, Math.min(g, b)),
      b = 1 - 1/255 * Math.max(r, Math.max(g, b));

  return [h, w * 100, b * 100];
}

b multiple declaration

**Comment by Qix-** [comment]
@phryniszak You're using a ridiculously old version. Please upgrade.

**Comment by phryniszak** [comment]
Fully agree:
"color-convert": "^0.5.3",

**Comment by kleptog** [comment]
@Qix- The issue is that chartjs-color hardcodes a dependancy on a really old version of color-convert. Would you accept a pull request to fix it?

**Comment by Qix-** [comment]
No. Please upgrade. There's no reason to be blocked using old software. If you can't upgrade your dependencies you're going to run into trouble anyway - might as well embrace it.

What do you mean it "hardcodes" a dependency?

**Comment by kleptog** [comment]
Well, current master has this:

https://github.com/chartjs/chartjs-color/blob/afb9254edef475c8cc6091da3eea2d5e1691068d/package.json#L36

```
  "dependencies": {
    "color-convert": "^0.5.3",
    "chartjs-color-string": "^0.5.0"
},
```

The current version of color-convert is 1.9.1.

**Comment by Qix-** [comment]
So upgrade. :P

**Comment by kleptog** [comment]
Upgrade what? I'm using the latest version of chartjs-color, and it depends on color-convert version ^0.5.3, as shown above. npm install selects version 1.9.1, that's not the problem (ansi-styles depends on ^1.9.0, the color package depends on ^1.9.1). However, if you are not using either of those packages (which apparently OP isn't), npm will install an old version 0.5.3 of color-convert which is broken.

My problem is related but different: all versions of color-convert < 0.7.0 have no defined licence in the package.json, which means license checking fails. But perhaps I should file a bug there instead.

**Comment by Qix-** [comment]
Yes - versions < 1.0.0 are not supported by me as I inherited the project and released 1.0.0 shortly after.

The chartjs-color folks should be the ones upgrading the package.

**Comment by kleptog** [comment]
Oh sorry, I thought you were the owner of the chartjs-color package since this is an issue on the chartjs-color repository. Oops! Never mind then.

**Comment by turnerniles** [comment]
@simonbrunel Would you accept a PR to upgrade the color-convert version?

**Comment by donmccurdy** [comment]
I'm getting warnings from my tools because the old version of `color-convert` doesn't specify a license. It would be helpful if this dependency could be updated, thanks. :)
