### ISSUE TITLE
Version 2.4.0 does not exist in npm

### ISSUE THREAD

**Issue by fruchtose** [chartjs/chartjs-color#7]
I see a release for version 2.4.0 here: https://github.com/chartjs/chartjs-color/tree/2.4.0

However, there is no corresponding 2.4.0 version in npm, and `package.json` still reports version `2.3.0` in master. Please fix so that people can take advantage of the dependency update from #6.

**Comment by kurkle** [comment]
Released 2.4.1 To fix this

**Comment by fruchtose** [comment]
Thank you!
